### ISSUE TITLE
APIClient.performAPIRequest() is not using SSL

### ISSUE THREAD

**Issue by FelixSFD** [SOBotics/SwiftStack#23]
The condition is this line is wrong:

https://github.com/SOBotics/SwiftStack/blob/master/Sources/APIClient.swift#L122

It uses `http`, if `useSSL` is `true`.

The line should be:

```
var url = "\(useSSL ? "https" : "http")://api.stackexchange.com/2.2"
```

**Comment by NobodyNada** [comment]
Thanks; fixed!
